version: '3.8'

services:
  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres
    environment:
      POSTGRES_DB: CatsShop
      POSTGRES_USER: cats_shop_user
      POSTGRES_PASSWORD: 4Tr0otuiQuU
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
